
services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: productos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  php:
    build: ./php
    container_name: php_app
    volumes:
      - ./php:/var/www/html/php
      - ./index.html:/var/www/html/index.html
      - ./js:/var/www/html/js
      - ./css:/var/www/html/css
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data:
