# Imagen base con PHP y Apache
FROM php:8.2-apache

RUN apt-get update && apt-get install -y \
        libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql \
    && a2enmod rewrite

COPY ./ /var/www/html/

# Permisos
RUN chown -R www-data:www-data /var/www/html

# Exponer puerto 80
EXPOSE 80
